source 'https://rubygems.org'

gem 'rake'
gem 'dashing', '>= 1.3.6'
gem 'json', '~> 1.7.7'
gem 'dotenv'
gem 'octokit', '>= 4.23.0'
gem 'i18n'
gem 'faraday', '~> 2.14', '>= 2.14.1'
gem 'faraday-http-cache', '>= 2.2.0'
gem 'activesupport'
gem 'rspec'
gem 'rspec-mocks'
gem "sentry-raven", :git => "https://github.com/getsentry/raven-ruby.git"
gem 'typhoeus'